"""Session 2026-07-02 (MAJOR REVISION): C5 environment note + Table T3 + flow disclosures.

Grounded facts:
  - Benchmark Cases 1-5 use E = 210,000 MPa (tests/benchmark/cases.py:42); Case 6 L-shape
    uses 210,000 MPa (case6_lshape.py:51, "both E = 210 GPa"); §5.2 IFC example uses 205,000
    (ifc_example_etabs_compare.json E_MPa=205000, P128/P132).
  - ifc_example_etabs_compare.json _meta.rigid_diaphragm = false; Case 4 is a bare 1x1 frame.
  - H-section Saint-Venant J = thin-walled (1/3)Sum(b*t^3) ~ 46-65% of catalog (memory).
  - §3.3.3 automatic IFC zone detection is implemented but the §5.3 L-shape is hand-assembled
    (not IFC-auto-detected); no irregular .ifc is auto-detected in the paper's validation.
  - CI (.github/workflows/ci.yml): pytest tests/ --ignore=tests/benchmark, SUPABASE_URL/KEY
    empty, Python 3.12.7; versions pinned in webapp/backend/requirements.txt. No offline DB
    fallback yet -> env note claims only what is TRUE (values archived + Appendix A), not a
    fallback that does not exist.

Edits:
  T3R5  Floor diaphragm value+note -> optional / off in reported cases (rigid_diaphragm=false).
  T3R7  Young's modulus note -> E per case (benchmark & L-shape 210; §5.2 IFC 205).
  P143  §5.3 ETABS sentence: append E = 210,000 MPa.
  P066  §3.4.2: append H-section open-section J approximation disclosure.
  P055  §3.3.3: append "zone auto-detection not exercised on an irregular IFC" disclosure.
  P181  Data availability: append a truthful reproducibility/computational-environment note.

Table 4 = d.tables[3]. Backup -> ..._v2.pre_c5t3_2026-07-02.docx. Dry-run default; --apply.
"""
from __future__ import annotations

import shutil
import sys
from pathlib import Path

import docx

ROOT = Path(__file__).resolve().parents[1]
DOC = ROOT / "docs" / "paper1_open_source_alternative" / "drafts" / "open_source_alternative_review_draft_v2.docx"
BACKUP = DOC.with_name("open_source_alternative_review_draft_v2.pre_c5t3_2026-07-02.docx")

# ---- table cell targets (Table 4 = d.tables[3]) ----
T3R5_VAL_OLD = "rigidDiaphragm"
T3R5_VAL_NEW = "Optional (off in the reported cases)"
T3R5_NOTE_OLD = "Per-story, tributary area mass distribution"
T3R5_NOTE_NEW = ("Per-story rigid diaphragm available but not applied in the benchmark cases "
                 "or the Section 5.2 IFC example (rigid_diaphragm = false); loads applied "
                 "directly to nodes and members")
T3R7_NOTE_OLD = ("Structural steel; identical value in OpenSeesPy and the commercial reference "
                 "for all benchmark cases")
T3R7_NOTE_NEW = ("Structural steel; identical value in OpenSeesPy and the commercial reference "
                 "within each comparison. The five benchmark cases and the Section 5.3 L-shape "
                 "example use 210,000 MPa; the Section 5.2 IFC application example uses the "
                 "SS275 KS value of 205,000 MPa")

# ---- paragraph run-replace (P143) ----
P143_OLD = "and the same tributary-distributed gravity loads."
P143_NEW = "the same tributary-distributed gravity loads, and a Young's modulus of E = 210,000 MPa."

# ---- paragraph appends ----
LOC_P066 = "all response quantities are transformed to a common textbook sign convention"
P066_APPEND = (
    " The Saint-Venant torsion constant of open I-sections is computed as the thin-walled "
    "approximation (1/3)Σbt³, which is conservative — roughly half of the tabulated catalog "
    "value; this is immaterial for the doubly-symmetric, torsionally uncoupled benchmark "
    "configurations of Section 4 but is a known limitation for general three-dimensional cases "
    "with significant torsional response."
)
LOC_P055 = "gravity loads on setbacks reflect the reduced active footprint at each story"
P055_APPEND = (
    " The automatic IFC zone-detection procedure described here is an implemented capability; "
    "the irregular-plan example in Section 5.3 is assembled directly as a node-element graph, "
    "and end-to-end zone auto-detection from an irregular IFC file is not exercised in the "
    "validation reported in this paper."
)
LOC_P181 = "reproduces the results reported in this paper"
P181_APPEND = (
    " The pipeline is implemented in Python 3.12 on OpenSeesPy, ifcopenshell, and NumPy, with "
    "package versions pinned in the repository; continuous integration runs the unit-test suite "
    "on each commit, and the five benchmark cases and the ETABS cross-checks are regenerated by "
    "the archived scripts using the bundled commercial reference values, so the "
    "response-quantity comparisons reproduce without a commercial license. The KDS load and "
    "hazard parameters are served from a hosted parameter database; the specific values used in "
    "this study are archived with the repository and enumerated clause-by-clause in Appendix A."
)

SENTINEL = "The Saint-Venant torsion constant of open I-sections"


def find_para(paras, needle, tag):
    hits = [p for p in paras if needle in p.text]
    if len(hits) != 1:
        raise SystemExit(f"ABORT [{tag}]: matched {len(hits)} (want 1): {needle[:50]!r}")
    return hits[0]


def run_replace(par, old, new, tag):
    for r in par.runs:
        if old in r.text:
            r.text = r.text.replace(old, new)
            return
    raise SystemExit(f"ABORT [{tag}]: substring not in a single run: {old[:40]!r}")


def cell_replace(cell, old, new, tag):
    if "fldChar" in cell._tc.xml or "instrText" in cell._tc.xml:
        raise SystemExit(f"ABORT [{tag}]: cell carries a field")
    for cpar in cell.paragraphs:
        for r in cpar.runs:
            if old in r.text:
                r.text = r.text.replace(old, new)
                return
        if old == cpar.text and cpar.runs:
            cpar.runs[0].text = new
            for r in cpar.runs[1:]:
                r.text = ""
            return
    raise SystemExit(f"ABORT [{tag}]: '{old[:30]}' not found in cell run")


def count_fields(d):
    xml = d.element.xml
    return xml.count("fldChar"), xml.count("instrText")


def main(apply: bool) -> int:
    d = docx.Document(str(DOC))
    paras = d.paragraphs
    if any(SENTINEL in p.text for p in paras):
        raise SystemExit("ABORT: already applied (P066 sentinel present).")

    fld0, ins0 = count_fields(d)
    np0, nt0, ni0 = len(paras), len(d.tables), len(d.inline_shapes)
    print(f"BEFORE: paragraphs={np0} tables={nt0} inline_shapes={ni0} fldChar={fld0} instrText={ins0}")

    t4 = d.tables[3]  # Table 4 (config params) == dump T3
    assert "diaphragm" in t4.rows[5].cells[0].text.lower(), f"row5 not diaphragm: {t4.rows[5].cells[0].text!r}"
    assert "modulus" in t4.rows[7].cells[0].text.lower(), f"row7 not modulus: {t4.rows[7].cells[0].text!r}"
    cell_replace(t4.rows[5].cells[1], T3R5_VAL_OLD, T3R5_VAL_NEW, "T3R5val")
    cell_replace(t4.rows[5].cells[2], T3R5_NOTE_OLD, T3R5_NOTE_NEW, "T3R5note")
    cell_replace(t4.rows[7].cells[2], T3R7_NOTE_OLD, T3R7_NOTE_NEW, "T3R7note")

    run_replace(find_para(paras, P143_OLD, "P143"), P143_OLD, P143_NEW, "P143")

    for loc, app, tag in [(LOC_P066, P066_APPEND, "P066"), (LOC_P055, P055_APPEND, "P055"),
                          (LOC_P181, P181_APPEND, "P181")]:
        par = find_para(paras, loc, tag)
        par.add_run(app)

    fld1, ins1 = count_fields(d)
    np1, nt1, ni1 = len(d.paragraphs), len(d.tables), len(d.inline_shapes)
    print(f"AFTER : paragraphs={np1} tables={nt1} inline_shapes={ni1} fldChar={fld1} instrText={ins1}")
    assert (fld1, ins1) == (fld0, ins0), f"FIELD COUNT CHANGED {fld0}/{ins0} -> {fld1}/{ins1}"
    assert (np1, nt1, ni1) == (np0, nt0, ni0), "structure count changed"

    print(f"\n--- T3R5 ---\n  val : {t4.rows[5].cells[1].text}\n  note: {t4.rows[5].cells[2].text}")
    print(f"\n--- T3R7 note ---\n  {t4.rows[7].cells[2].text}")
    print(f"\n--- P143 tail ---\n{find_para(d.paragraphs, 'E = 210,000 MPa', 'x').text[-200:]}")
    print(f"\n--- P066 tail ---\n{find_para(d.paragraphs, SENTINEL, 'x').text[-320:]}")
    print(f"\n--- P055 tail ---\n{find_para(d.paragraphs, 'end-to-end zone auto-detection', 'x').text[-280:]}")
    print(f"\n--- P181 tail ---\n{find_para(d.paragraphs, 'hosted parameter database', 'x').text[-360:]}")

    if not apply:
        print("\nDRY-RUN (no save). Re-run with --apply to write.")
        return 0
    shutil.copy2(DOC, BACKUP)
    print(f"\nbackup -> {BACKUP.name}")
    d.save(str(DOC))
    print(f"SAVED -> {DOC.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(apply="--apply" in sys.argv))
