"""Generate Midas Gen 2019 MCT file for Case 6 L-shape model.

Reads:
    tests/benchmark/case6_lshape_loadtables.json — load tables + diaphragm masters
    (and re-builds the L-shape model via build_l_shape_model() for node/element data)

Writes:
    scripts/case6_lshape_input.mct — ready for File → Import → Midas MCT File

Unit system in MCT: N, MM
    - E = 205,000 N/mm² (= 205 GPa)
    - Beam line load: kN/m == N/mm (numerically equal — no conversion)
    - Nodal force: kN × 1000 → N
    - Coordinates: m × 1000 → mm
    - Section dimensions: mm

NOTE on MCT syntax:
    Midas MCT command tokens (especially RIGIDLINK, SECTION DBUSER, BEAMLOAD)
    can vary slightly between Midas Gen versions. This script targets the
    common Midas Gen 2019 format. If import warns or fails on a specific
    block, the simplest fix is to:
      (a) for RIGIDLINK: skip the block and add rigid floors via
          Boundary → Rigid Link UI (5 entries; takes ~2 min).
      (b) for SECTION: redefine sections via Property → Section UI.
    The dominant load entries (156 BEAMLOAD + 110 CONLOAD) follow a stable
    syntax and should import cleanly.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

_THIS = Path(__file__).resolve()
_REPO = _THIS.parent.parent
sys.path.insert(0, str(_REPO / "mcp-server"))
sys.path.insert(0, str(_REPO / "tests"))

from test_v2_irregular import build_l_shape_model  # noqa: E402


def _mm(v_m: float) -> int:
    """Convert meters to millimeters (rounded int — coordinates are clean multiples)."""
    return int(round(v_m * 1000))


def _format_num(v: float, decimals: int = 6) -> str:
    """Format a number, trimming trailing zeros for cleaner MCT output."""
    s = f"{v:.{decimals}f}".rstrip("0").rstrip(".")
    return s if s else "0"


def generate_mct() -> str:
    model = build_l_shape_model()
    handoff_path = _REPO / "tests" / "benchmark" / "case6_lshape_loadtables.json"
    with open(handoff_path, encoding="utf-8") as f:
        handoff = json.load(f)

    masters = handoff["rigid_diaphragm_master_per_story"]   # {"1": 38, ...}
    dl_loads = handoff["DL_line_loads_kNm"]
    ll_loads = handoff["LL_line_loads_kNm"]
    lateral_table = handoff["lateral_force_table_kN"]

    col_section_id = 1
    beam_section_id = 2

    L = []
    A = L.append

    # ── Header ──
    A("; ============================================================")
    A("; Case 6 — L-shape Decision-Gate Validation (5F + 3F setback)")
    A("; Auto-generated by scripts/generate_case6_mct.py")
    A("; Source spec  : scripts/_case6_lshape_spec.md")
    A("; Load tables  : tests/benchmark/case6_lshape_loadtables.json")
    A("; UI guide     : scripts/_case6_lshape_midas_guide_kr.md")
    A(";")
    A("; Unit system  : N, MM (input)")
    A(";   E = 205,000 N/mm² (= 205 GPa)")
    A(";   1 kN/m line load == 1 N/mm (numerically equal)")
    A(";   Nodal force: kN × 1000 → N")
    A("; ============================================================")
    A("")

    # ── Version + Unit ──
    A("*VERSION")
    A("   2.1.0")
    A("")
    A("*UNIT    ; Unit System")
    A("   N, MM, KJ, C")
    A("")

    # ── Structure Type ──
    A("*STRUCTYPE")
    A("; iSTRTYPE, iMASSTYPE, GRAVITY, bYDIR, bMASS, MASSDIR, GLOBAL_Z")
    A("   0, 1, 9806, NO, YES, XYZ, 0")
    A("")

    # ── Material — SS275 (User-Defined to enforce E = 205,000) ──
    A("*MATERIAL")
    A(";  iMAT, TYPE, MNAME, SPHEAT, HEATCO, PLAST, TUNIT, MAR, [DATA1]")
    A(";  [DATA2] : ELAST, POISN, THERMAL, DEN, MASS")
    A("   1, USER, SS275, 0, 0, , C, 0, , NO")
    A("       205000, 0.3, 1.2e-05, 0, 0")
    A("")

    # ── Sections (H-300x300 column, H-400x200 beam) ──
    A("*SECTION")
    A(";  iSEC, TYPE, SNAME, [OFFSET], bSD, SHAPE, [DATA1]")
    A(";    SHAPE=H : H, B1, tw, tf1, B2, tf2, r1, r2")
    A(f"   {col_section_id},  DBUSER, H300x300, CC, 0, 0, 0, 0, 0, 0, 0, YES, NO, H, 2, , 300, 300, 10, 15, 300, 15, 0, 0")
    A(f"   {beam_section_id}, DBUSER, H400x200, CC, 0, 0, 0, 0, 0, 0, 0, YES, NO, H, 2, , 400, 200,  8, 13, 200, 13, 0, 0")
    A("")

    # ── Nodes ──
    A("*NODE")
    A(";  iNO, X, Y, Z   (mm)")
    for n in sorted(model.nodes.values(), key=lambda x: x.id):
        A(f"   {n.id}, {_mm(n.x)}, {_mm(n.y)}, {_mm(n.z)}")
    A("")

    # ── Elements (BEAM type for both columns and beams; Beta=0) ──
    A("*ELEMENT")
    A(";  iEL, TYPE, iMAT, iPRO, iN1, iN2, ANGLE, iSUB")
    for e in sorted(model.elements.values(), key=lambda x: x.id):
        sid = col_section_id if e.elem_type == "column" else beam_section_id
        A(f"   {e.id}, BEAM, 1, {sid}, {e.node_i}, {e.node_j}, 0, 0")
    A("")

    # ── Boundary (FIXED 6-DOF at z = 0 nodes) ──
    A("*CONSTRAINT")
    A(";  NODE_LIST, CONST(Dx,Dy,Dz,Rx,Ry,Rz)")
    base_nodes = sorted(n.id for n in model.nodes.values() if abs(n.z) < 0.01)
    for nid in base_nodes:
        A(f"   {nid}, 111111")
    A("")

    # ── Rigid Diaphragm per Story (Plate XY: Dx, Dy, Rz constrained) ──
    # DOF mask 6-bit: Dx Dy Dz Rx Ry Rz → 110001
    # Format may vary by Midas version. If import warns, replace this block with
    # manual Rigid Link entries via UI (Boundary → Rigid Link). 5 entries only.
    A("; ──────────────────────────────────────────────────────────")
    A("; RIGIDLINK (Plate XY diaphragm: Dx, Dy, Rz constrained)")
    A("; If import skips this section, add 5 rigid links via UI:")
    A(";   Boundary → Rigid Link → Plate type")
    A(";   Master node + slave list per story (see comments below)")
    A("; ──────────────────────────────────────────────────────────")
    A("*RIGIDLINK")
    A(";  MASTER, DOF(110001=Dx,Dy,Rz), SLAVE_LIST")
    for s_str, master_id in masters.items():
        s = int(s_str)
        slaves = sorted(
            n.id for n in model.nodes.values()
            if n.story == s and n.id != master_id
        )
        slave_str = " ".join(str(x) for x in slaves)
        A(f"; --- Story {s}F: master={master_id}, {len(slaves)} slaves ---")
        A(f"   {master_id}, 110001, {slave_str}")
    A("")

    # ── Static Load Cases ──
    A("*STLDCASE")
    A(";  LCNAME, LCTYPE, DESC")
    A('   DL, D, "Dead 5.1 kN/m² floor area → beam line loads"')
    A('   LL, L, "Live 2.5 kN/m² floor area → beam line loads"')
    A('   EQX, E, "EQ X total V_base=500 kN, inv-tri, per-node nodal Fx"')
    A('   EQY, E, "EQ Y total V_base=500 kN, inv-tri, per-node nodal Fy"')
    A("")

    # ── DL Beam Loads ──
    # kN/m == N/mm so w_line is used as-is (downward → minus)
    A("*USE-STLD, DL")
    A("*BEAMLOAD")
    A(";  iEL, CMD, TYPE, DIR, ProjType, D1, V1, D2, V2, D3, V3, D4, V4, GROUP")
    for ld in dl_loads:
        w = ld["w_line_kNm"]
        w_str = _format_num(w, 6)
        A(f"   {ld['elem_id']}, BEAM, UNILOAD, GZ, NO, 0, -{w_str}, 1, -{w_str}, 0, 0, 0, 0, ")
    A("")

    # ── LL Beam Loads ──
    A("*USE-STLD, LL")
    A("*BEAMLOAD")
    A(";  iEL, CMD, TYPE, DIR, ProjType, D1, V1, D2, V2, D3, V3, D4, V4, GROUP")
    for ld in ll_loads:
        w = ld["w_line_kNm"]
        w_str = _format_num(w, 6)
        A(f"   {ld['elem_id']}, BEAM, UNILOAD, GZ, NO, 0, -{w_str}, 1, -{w_str}, 0, 0, 0, 0, ")
    A("")

    # ── EQX Nodal Loads ──
    A("*USE-STLD, EQX")
    A("*CONLOAD")
    A(";  NODE, FX, FY, FZ, MX, MY, MZ, GROUP")
    for row in lateral_table:
        per_node_N = row["per_node_kN"] * 1000.0
        f_str = _format_num(per_node_N, 4)
        A(f"; Story {row['story']}F (z={row['z_m']}m) per-node Fx = {f_str} N")
        for nid in row["node_ids"]:
            A(f"   {nid}, {f_str}, 0, 0, 0, 0, 0, ")
    A("")

    # ── EQY Nodal Loads ──
    A("*USE-STLD, EQY")
    A("*CONLOAD")
    A(";  NODE, FX, FY, FZ, MX, MY, MZ, GROUP")
    for row in lateral_table:
        per_node_N = row["per_node_kN"] * 1000.0
        f_str = _format_num(per_node_N, 4)
        A(f"; Story {row['story']}F (z={row['z_m']}m) per-node Fy = {f_str} N")
        for nid in row["node_ids"]:
            A(f"   {nid}, 0, {f_str}, 0, 0, 0, 0, ")
    A("")

    # ── Closing ──
    A("*ENDDATA")
    A("")

    return "\n".join(L)


def main() -> None:
    out_path = _THIS.parent / "case6_lshape_input.mct"
    content = generate_mct()
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(content)

    # Stats
    n_lines = content.count("\n")
    n_chars = len(content)
    n_data_lines = sum(
        1 for line in content.split("\n")
        if line.strip() and not line.strip().startswith(";") and not line.strip().startswith("*")
    )

    print(f"Generated: {out_path}")
    print(f"  Total lines        : {n_lines}")
    print(f"  Data lines (non-cmt): {n_data_lines}")
    print(f"  Size               : {n_chars:,} chars")
    print("")
    print("Import into Midas Gen 2019:")
    print("  File → Import → Midas MCT File → select the file above")
    print("")
    print("Pre-check the imported model:")
    print("  - Property → Material : SS275 with E = 205,000 N/mm²")
    print("  - Property → Section  : H-300x300, H-400x200")
    print("  - 70 nodes, 135 elements, 13 fixed supports")
    print("  - 5 rigid diaphragms (verify Slave list on 4F, 5F excludes Zone B)")
    print("  - 4 load cases: DL, LL, EQX, EQY")


if __name__ == "__main__":
    main()
